version: '3.8'

services:
    database:
        image: postgres:12.3-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports: [5432]


